class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/clzs_test022/lj/long/tbsi'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/clzs_test022/lj/long/tbsi/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/clzs_test022/lj/long/tbsi/pretrained_networks'
        self.lasot_dir = '/clzs_test022/dataset/rbgt_tracking/lasot'
        self.got10k_dir = '/clzs_test022/dataset/rbgt_tracking/got10k/train'
        self.got10k_val_dir = '/clzs_test022/dataset/rbgt_tracking/got10k/val'
        self.lasot_lmdb_dir = '/clzs_test022/dataset/rbgt_tracking/lasot_lmdb'
        self.got10k_lmdb_dir = '/clzs_test022/dataset/rbgt_tracking/got10k_lmdb'
        self.trackingnet_dir = '/clzs_test022/dataset/rbgt_tracking/trackingnet'
        self.trackingnet_lmdb_dir = '/clzs_test022/dataset/rbgt_tracking/trackingnet_lmdb'
        self.coco_dir = '/clzs_test022/dataset/rbgt_tracking/coco'
        self.coco_lmdb_dir = '/clzs_test022/dataset/rbgt_tracking/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/clzs_test022/dataset/rbgt_tracking/vid'
        self.imagenet_lmdb_dir = '/clzs_test022/dataset/rbgt_tracking/vid_lmdb'
        self.lasher_train_dir = '/clzs_test022/dataset/rbgt_tracking/lasher/trainingset'
        self.lasher_test_dir = '/clzs_test022/dataset/rbgt_tracking/lasher/testingset'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
